import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {},

  client: {
    NEXT_PUBLIC_AUTHOR_NAME: z.string().min(1),
    NEXT_PUBLIC_AUTHOR_FIRST_NAME: z.string().min(1),
    NEXT_PUBLIC_AUTHOR_LAST_NAME: z.string().min(1),
    NEXT_PUBLIC_AUTHOR_TITLE: z.string().min(1),
    NEXT_PUBLIC_AUTHOR_PHONE: z.string().min(1),
    NEXT_PUBLIC_AUTHOR_EMAIL: z.string().min(1),
    NEXT_PUBLIC_AUTHOR_LINKEDIN: z.string().min(1),
    NEXT_PUBLIC_AUTHOR_GITHUB: z.string().min(1),
    NEXT_PUBLIC_AUTHOR_X: z.string().min(1),
    NEXT_PUBLIC_AUTHOR_LOCATION: z.string().min(1),
    NEXT_PUBLIC_AUTHOR_BIO: z.string().min(1),
    NEXT_PUBLIC_AUTHOR_LIVE_RESUME: z.string().min(1),
  },

  runtimeEnv: {
    NEXT_PUBLIC_AUTHOR_NAME: process.env.NEXT_PUBLIC_AUTHOR_NAME,
    NEXT_PUBLIC_AUTHOR_FIRST_NAME: process.env.NEXT_PUBLIC_AUTHOR_FIRST_NAME,
    NEXT_PUBLIC_AUTHOR_LAST_NAME: process.env.NEXT_PUBLIC_AUTHOR_LAST_NAME,
    NEXT_PUBLIC_AUTHOR_TITLE: process.env.NEXT_PUBLIC_AUTHOR_TITLE,
    NEXT_PUBLIC_AUTHOR_PHONE: process.env.NEXT_PUBLIC_AUTHOR_PHONE,
    NEXT_PUBLIC_AUTHOR_EMAIL: process.env.NEXT_PUBLIC_AUTHOR_EMAIL,
    NEXT_PUBLIC_AUTHOR_LINKEDIN: process.env.NEXT_PUBLIC_AUTHOR_LINKEDIN,
    NEXT_PUBLIC_AUTHOR_GITHUB: process.env.NEXT_PUBLIC_AUTHOR_GITHUB,
    NEXT_PUBLIC_AUTHOR_X: process.env.NEXT_PUBLIC_AUTHOR_X,
    NEXT_PUBLIC_AUTHOR_LOCATION: process.env.NEXT_PUBLIC_AUTHOR_LOCATION,
    NEXT_PUBLIC_AUTHOR_BIO: process.env.NEXT_PUBLIC_AUTHOR_BIO,
    NEXT_PUBLIC_AUTHOR_LIVE_RESUME: process.env.NEXT_PUBLIC_AUTHOR_LIVE_RESUME,
  },
});
